### ISSUE TITLE
Add options for answers and foreign characters like ěščřžýáíé

### ISSUE THREAD

**Issue by wowquester** [sinahmr/exam-generator#2]
Hey sinahmr, as a teacher I really appreciate this code and I will use it for my generating exams. 
Do you think you could add (or just give a hint here in the comments if you dont wont to modify rep) ABCDE options?

Like:
![Screenshot 2023-08-09 at 21 49 43](https://github.com/sinahmr/exam-generator/assets/138876396/134b1aa7-aef5-403b-bbc7-c4688170295d)
(with proper spacing, not just a space)

I'd do it myself, but my python/tex skill is insufficient for this.

Also it seem like letters ščřžýáíé and so on tends to give errors. Do you thin you could take a look?
When I modify the question:
\begin{question}
Otázka 987žšč_\\
\begin{center}
a) 1	 b) 2	c) 3	d) 4
\end{center}
\end{question}
\begin{solution}
solution_text
\end{solution}

I get this LaTeX errors:
! LaTeX Error: \begin{document} ended by \end{question}.
or
.2 Otá
        zka 987šč_\\
This error message was generated by an \errmessage
command, so I can't give any explicit help.
Pretend that you're Hercule Poirot: Examine all clues,
and deduce the truth by order and method.

LaTeX Font Warning: Font shape `/cmr/m/n' undefined
(Font)              using `OT1/cmr/m/n' instead on input line 2.

Missing character: There is no z in font nullfont!
Missing character: There is no k in font nullfont!
Missing character: There is no a in font nullfont!
Missing character: There is no 9 in font nullfont!
Missing character: There is no 8 in font nullfont!
Missing character: There is no 7 in font nullfont!
! Missing $ inserted.
<inserted text> 
                $
l.2 Otázka 987šč_

Thanks in advance!
I'll learn py with TeX once, but for now you're the only hope.

**Comment by sinahmr** [comment]
Hi,
Thanks for your interest.

About the multi-option questions, nothing in the code needs changing, you can search for how to do it in TeX. For example, [this page](https://tex.stackexchange.com/questions/504629/nicely-spaced-multiple-choice-options) might help you.

I'm not sure of the language that you wish to use, but having a look at [this page](https://latex.org/forum/viewtopic.php?t=15421) might help you solve that problem.

I'm sorry I don't have the time to make sure I'm giving the right answers, so take these with a grain of salt.
